### ISSUE TITLE
No file "temp.bin'' in supervoxel_cluster

### ISSUE THREAD

**Issue by penghaohsu0222** [Pokerlishao/LoopGaussian#1]
Hi, thanks for your interesting work!
When I'm running "train_loop.py", it seems a file missing during supervoxel_cluster after finish training PAE.

![截圖 2024-05-22 上午12 18 23](https://github.com/Pokerlishao/LoopGaussian/assets/114682066/073c0027-39a8-4a9f-a8e9-66520024b5b3)

How can I get the file "temp.bin"?
Thank you.

**Comment by Pokerlishao** [comment]
Hi, thank you for your interest in our work!

The problem you encountered is due to a missing `libsupervoxel.so` file, not the `temp.bin` file. The `temp.bin` file is a temporary file that is automatically created and destroyed at runtime.
I have uploaded the relevant files, and you can re-run `bash train_loop.sh $task_name` to try again.
This should resolve the issue. Let me know if you encounter any further problems.

Best regards.

**Comment by penghaohsu0222** [comment]
If I export `export LD_LIBRARY_PATH=$LIB_PATH/CinemaGaussian/lib`, the original environment variables will be replaced so the file like `libpython3.11.so.1.0` cannot be read.

**Comment by Pokerlishao** [comment]
It seems you may have missed part of the command. Instead of replacing the original environment variables, you should append the new path using: `export LD_LIBRARY_PATH=$LIB_PATH/CinemaGaussian/lib:$LD_LIBRARY_PATH`. This will add the new path to the existing environment variables rather than replacing them.

Let me know if you need any further assistance.

**Comment by penghaohsu0222** [comment]
![截圖 2024-05-22 下午6 32 34](https://github.com/Pokerlishao/LoopGaussian/assets/114682066/768c61f5-c83b-4346-b73f-ce6e0d6aca22)

Here is a new question about version `GLIBC_2.34`. The environment of LoopGaussian is installed following the repo.
Thanks for your replies.

**Comment by Pokerlishao** [comment]
This issue might be caused by the OS version. I am running it on Ubuntu 22.04. If you are using an older version of Ubuntu, you can refer to this [link](https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found) or this [link](https://blog.csdn.net/huazhang_001/article/details/128828999), which may be helpful.
Please note that manually editing sources is not recommended, so proceed with caution.

**Comment by sauradip** [comment]
I am having this error 
![Screenshot from 2024-06-22 20-27-43](https://github.com/Pokerlishao/LoopGaussian/assets/23197350/f36e54f5-7dec-4d47-850a-88b38eca052f)
